### PR TITLE
Fix: #8. ld+yaml mediatype

### PR DESCRIPTION
**Pull request by ioggstream**
## This PR

- registers the application/ld+yaml media type
- registers the .yamlld file extension

### CODE REVIEW

**Comment by pchampin** [comment]
I like the idea of YAML-LD :)
Although it should is relatively straightforward, the devil is in the detail, and I believe some details should be explicitly ironed up. For example, IIRC, YAML is a superset of JSON. What is a processor supposed to do with YAML construct that do not map to JSON? Ignore them? Reject them as an error? Note that the answer may be different depending on where this happens (in data vs. in context).

**Comment by gkellogg** [comment]
As both @pchampin and @msporny mentioned (in https://github.com/ietf-wg-httpapi/mediatypes/issues/8#issuecomment-1015495947), it is important that the YAML used be restricted to just use native JSON features to insure backwards and forwards compatibility with JsON-LD.

**Comment by ioggstream** [comment]
Moved to another project: https://github.com/json-ld/yaml-ld

**Comment by VladimirAlexiev** [comment]
Hi @ioggstream @pchampin @ivanherman!
https://www.iana.org/assignments/media-types/media-types.xhtml#application

**Comment by ioggstream** [comment]
Hi @VladimirAlexiev. This PR has been closed because we decided to move the LD stuff to github.com/json-ld/yaml-ld :) 

I will double-check the https://github.com/w3c/json-ld-syntax/issues/385 to ensure that all registration parameters are ok.

**Pull request closed without merging**
